config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  get 'pages/home'
  get 'pages/dashboard'
  get 'plainpage/index'

  resources :companies
  resources :clients
  resources :projects
  resources :timesheets
  resources :invoices
  resources :spendings
  resources :annualaccounts
  resources :mileages

  get 'companies/edit'
  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
    belongs_to :client

    validates :invoice_date, presence: true
    validates :invoice_client_name, presence: true
    validates :invoice_subject, presence: true
    validates :invoice_VAT_number, presence: true


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :find_invoice, only: [:test, :edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index
        @invoices = Invoice.all
    end

    def new
        @invoice = Invoice.new
    end
    
    def test
        @invoice.update_attributes(:invoice_VAT_number => 1000 )
    end
    
    
    def create
        @invoice = Invoice.new invoice_params
        
        if @invoice.save
            flash[:notice] = "De factuur is opgeslagen!"
            redirect_to action: "index"
        else
            render 'new'
            flash[:notice] = "Oh nee! De factuur is niet opgeslagen."
        end
    end
    
    def edit
    end
    
    def update
        if @invoice.update invoice_params
            flash[:notice] = "Uw factuurinfo is succesvol aangepast."
            redirect_to action: "index"
        else
            flash[:notice] = "Oh nee! Uw factuurinfo kon niet opgeslagen worden."
            render 'edit'
        end
    end
    
    def destroy
        @invoice.destroy
        redirect_to action: "index"
    end
    
    private
    
    def invoice_params
        params.require(:invoice).permit(:invoice_number, :invoice_date, :invoice_client_name, :invoice_subject, :invoice_VAT_number, :invoice_VAT_percentage, :invoice_exclusive_VAT, :invoice_VAT, :invoice_including_VAT, :invoice_when_paid, :invoice_paid, :invoice_left)
    end
    
    def find_invoice
       @invoice = Invoice.find(params[:id]) 
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="col-xs-12">
  <div id="invoice-wrap">
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">FACTUUR<small class="pull-right">Datum: <span class="invoice_header_date"></span></small></h3>
      </div><!-- /.col -->
    </div>

    <div class="row">
      <div class="col-xs-12 table-responsive">
        <hr>
        <table class="table table-hover" id="items">
      
          <thead>
              <th class="item-name">Item</th>
              <th class="description">Beschrijving</th>
              <th class="unit">Kosten per eenheid</th>
              <th class="quantity">Hoeveelheid</th>
              <th class="units">Prijs</th>
              <th class="no_print">Acties</th>
      
          <tbody>
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #1" /></td>
              <td><input class="form-control item_desc" value="Beschrijving" /></td>
              <td><input class="form-control cost" value="650.00" /></td>
              <td><input class="form-control qty" value="1" /></td>
              <td class="price_td"><span class="price">650.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="fa fa-times"></span></a></td>
            </tr>
          
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #2" /></td>

              <td><input class="form-control item_desc" value="Beschrijving #2" /></td>
              <td><input class="form-control cost" value="75.00" /></td>
              <td><input class="form-control qty" value="3" /></td>
              <td class="price_td"><span class="price">225.00</span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="fa fa-times"></span></a></td>
            </tr>
          
            <tr id="hiderow">
              <td colspan="6"><a id="addrow" class="btn btn-success btn-sm" href="javascript:;" title="Add a row"><span class="ti-plus"></span> Voeg rij toe</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-xs-offset-6">
        <div class="table-responsive">
          <table class="table table-hover" id="totals">
            <tr>
              <th style="width:50%">Subtotaal:</th>
              <td><span id="subtotal">875.00</span><span class="subtotal_currency"></span></td>
            </tr>
            <tr>
              <th>Belasting percentage:</th>
              <td><input id="9" class="form-control" value="0.00" /></td>
            </tr>
            <tr>
              <th>Totaal:</th>
              <td class="balance"><span class="due" id="invoice_total">875.00</span><span class="subtotal_currency"></span></td>
            </tr>
          </table>
        </div>
      </div><!-- /.col -->    
    </div>

    <div class="row">
      <div class="col-xs-12 pull-left">
        <a class="btn btn-info btn-sm" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">Bekijk factuur</a>
      </div>
    </div>

    <div id="terms">
      <h5>Voorwaarde</h5>
      <textarea id="10">Betalingsvoorwaarde: net 30. Interest accrued at 1.5% per month thereafter.</textarea>
    </div>
  </div>
</div>

<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width:920px">
      <div class="container-fluid invoice_wrapper" style="margin:10px" id="print-me">
        <%= render 'invoice' %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="printDiv('print-me')">Print</button>
      </div>
    </div>
  </div>
</div>

<%= form_for @invoice, :html => {:class => 'form-horizontal form-label-left'} do |f| %>
    <% if @invoice.errors.any? %>
        <h2><%= pluralize(@invoice.errors.count, "error")%> zorgde ervoor dat de klant niet opgeslagen kon worden.</h2>
        <ul>
            <% @invoice.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    
    <div class="form-group">
        <%= f.label :invoice_number, 'Factuur nummer', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.number_field :invoice_number, class: 'form-control col-md-7 col-xs-12', id: 'invoicing_number' %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :invoice_date, 'Factuur datum', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :invoice_date, id: 'datepicker', class: 'form-control col-md-7 col-xs-12' %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :invoice_client_name, 'Naam Opdrachtgever', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.collection_select(:invoice_client_name, Client.all, :client_name, :client_name, include_blank: true, class: 'form-control', id: 'client_name') %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :invoice_subject, 'Onderwerp', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :invoice_subject, class: 'form-control col-md-7 col-xs-12' %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :invoice_VAT_number, 'BTW nummer', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :invoice_VAT_number, class: 'form-control col-md-7 col-xs-12' %><br>
        </div>
    </div>
    
    <%= f.hidden_field :invoice_VAT_percentage, :html => {:id => "invoice_VAT_percentage"}  %>
    <%= f.hidden_field :invoice_exclusive_VAT, :html => {:id => "invoice_exclusive_VAT"}  %>
    
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Annuleren', invoices_path, :class => 'btn btn-primary' %>
      <%= f.submit 'Opslaan', :class => 'btn btn-success', :id => 'invoicing' %>
    </div>

<% end %>
    

app/views/invoices/_invoice.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="page-header">
      FACTUUR
      <small class="pull-right">Datum: <span class="invoice_header_date"></span></small>
    </h3>
  </div><!-- /.col -->
</div>
                <!-- info row -->
<div class="row invoice-info">
  <div class="col-xs-4 invoice-col">
    Van
    <address>
      <div id= "modal_1" class="bold"></div>
      <div id= "modal_2"></div>
      <div id= "modal_3"></div>
      <div id= "modal_4"></div>

    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    Naar
    <address>
      <div id= "modal_5"></div>
      <div id= "modal_6"></div>
      <div id= "modal_7"></div>
      <div id= "modal_8"></div>
    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-xs-5"><label>Factuur #</label></div>
        <div class="col-xs-7"><p id="modal_invoice_number" class="pull-right"></p></div>
      </div>
                    
      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-4"><label>Datum</label></div>
        <div class="col-xs-8"><span class="invoice_header_date pull-right"></span></div>
      </div>
                    
      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-5 invoice_space"><label>Verschuldigd</label></div>
        <div class="col-xs-7 invoice_space bold" style="text-align:right"><span class="due">875.00</span><span class="subtotal_currency"></span></div>
      </div>
    </form>
  </div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
	<div class="col-xs-12">
    <hr>
		<table class="table table-bordered" id="modal_items">
		  <thead>
		    <th class="item-name">Item</th>
		    <th class="description">Beschrijving</th>
		    <th class="unit">Kosten per eenheid</th>
	      <th class="quantity">Hoeveelheid</th>
	      <th class="units">Prijs</th>
		  </thead>
		  
		  <tbody id="modal_tbody">
		  </tbody>
		</table>

	</div>
</div>

<div class="row">
	<div class="col-xs-6 col-xs-offset-6">
    <div class="">
      <table class="table" id="modal_totals">
        <tr>
          <th style="width:50%">Subtotaal:</th>
          <td><span id="modal_subtotal"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Belasting percentage:</th>
          <td><span id="modal_9"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Totaal:</th>
          <td class="balance"><span class="due">875.00</span><span class="subtotal_currency"></span></td>
        </tr>
      </table>
    </div>
  </div><!-- /.col -->
</div>

<div id="modal_terms">
	<h5>Voorwaarde</h5>
	<span id="modal_10"></span>
</div>

app/views/invoices/edit.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Edit factuur</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Wijzig <%= @invoice.invoice_number %></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
              <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/invoices/index.html.erb
<!-- page content -->
<div class="right_col" role="main" style="height:100vh">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Factureren</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Uw concepten:</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                    <th class="column-title">Factuur nummer</th>
                    <th class="column-title">Datum</th>
                    <th class="column-title">Naam Opdrachtgever</th>
                    <th class="column-title">Onderwerp</th>
                    <th class="column-title">BTW nummer</th>
                    <th class="column-title">BTW %</th>
                    <th class="column-title">Bedrag ex BTW</th>
                    <th class="column-title">BTW</th>
                    <th class="column-title">Bedrag incl BTW</th>
                    <th class="column-title">Acties</th>
                </tr>
              </thead>
            <% @invoices.each do |invoice| %>
              <tbody>
                  <tr>
                    <td><%= invoice.invoice_number %></td>
                    <td><%= invoice.invoice_date %></td>
                    <td><%= invoice.invoice_client_name %></td>
                    <td><%= invoice.invoice_subject %></td>
                    <td><%= invoice.invoice_VAT_number %></td>
                    <td><%= invoice.invoice_VAT_percentage %>%</td>
                    <td>€ <%= invoice.invoice_exclusive_VAT %></td>
                    <td>
                        <% som_BTW = invoice.invoice_VAT_percentage * 0.01 * invoice.invoice_exclusive_VAT %>
                        <% invoice.invoice_VAT = som_BTW %>
                        € <%= invoice.invoice_VAT %>
                    </td>
                    <td> 
                        <% invoice.invoice_including_VAT = invoice.invoice_VAT + invoice.invoice_exclusive_VAT %>
                        € <%= invoice.invoice_including_VAT %>
                    </td>
                    <td>
                    <%= link_to edit_invoice_path(invoice) do %>
                        <img src="/images/pencil-edit-button.png" alt="Delete" class="edit_icon">
                    <% end %>
                    <%= link_to invoice_path(invoice), method: :delete, data: { confirm: "Weet je zeker dat je deze klant wilt verwijderen" } do %>
                        <img src="/images/delete.png" alt="Wijzig" class="edit_icon">
                    <% end %>
                    </td>
                  </tr>
              </tbody>
            <% end %>
            </table>
            <div class="col-md-6 col-md-offset-5">
                <%= link_to new_invoice_path do %>
                    <button class="btn btn-primary">Nieuwe factuur</button>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/invoices/new.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nieuwe factuur</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Maak een factuur aan:</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
              <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->