config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  get 'pages/home'
  get 'pages/dashboard'
  get 'plainpage/index'

  resources :companies
  resources :clients
  resources :projects
  resources :timesheets
  resources :invoices
  resources :spendings
  resources :annualaccounts
  resources :mileages

  get 'companies/edit'
  

end

app/models/annualaccount.rb
class Annualaccount < ActiveRecord::Base
    validates :an_date, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
    belongs_to :company
    has_many :invoices
    has_many :projects
    
    validates :client_number, presence: true
    validates :client_name, presence: true
    validates :client_contact_person, presence: true, uniqueness: true
    validates :client_address, presence: true, uniqueness: true
    validates :client_zipcode, presence: true, uniqueness: true
    validates :client_residence, presence: true
    validates :client_gender, presence: true
    validates :client_phone, presence: true
    validates :client_email, presence: true
    validates :client_account_number, presence: true, uniqueness: true

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :users
    has_many :clients
    has_many :projects
    has_many :spendings
    
    validates :company_name, presence: true
    validates :company_address, presence: true
    validates :company_zipcode, presence: true
    validates :company_place, presence: true
    validates :company_phone, presence: true, length: {maximum: 10}
    validates :company_email, presence: true
    validates :company_webaddress, presence: true
    validates :company_bank_account_number, presence: true
    validates :company_bank, presence: true
    validates :company_VAT_number, presence: true
    validates :company_CC_number, presence: true

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
    belongs_to :client

    validates :invoice_date, presence: true
    validates :invoice_client_name, presence: true
    validates :invoice_subject, presence: true
    validates :invoice_VAT_number, presence: true


end

app/models/mileage.rb
class Mileage < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :company
    belongs_to :client
    
    validates :project_name, presence: true
    validates :project_client, presence: true
    validates :project_budget, presence: true

end

app/models/spending.rb
class Spending < ActiveRecord::Base
    belongs_to :company
    
    validates :spending_date, presence: true
    validates :spending_company_name, presence: true
    validates :spending_cost_description, presence: true
    validates :spending_type, presence: true
    validates :spending_exclusive_VAT, presence: true
    validates :spending_VAT, presence: true
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
    belongs_to :client
    has_and_belongs_to_many :projects
    
    validates :timesheet_project_number, presence: true
    validates :timesheet_name, presence: true
    validates :timesheet_description, presence: true
    validates :timesheet_date, presence: true
    validates :timesheet_hours, presence: true
    validates :timesheet_comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :company
  
  validates :company_id, presence: true
  validates :user_name, presence: true
  validates :user_gender, presence: true
  validates :user_function, presence: true
  validates :user_phone, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :find_client, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @clients = Client.all
    end
    
    def new
        @client = Client.new
    end
    
    def create
        @client = Client.new client_params
        
        if @client.save
            flash[:notice] = "De klant is opgeslagen!"
            redirect_to action: "index"
        else
            render 'new'
            flash[:notice] = "Oh nee! De klant is niet opgeslagen."
        end
    end
    
    def edit
    end
    
    def update
        if @client.update client_params
            flash[:notice] = "Uw klanteninfo is succesvol aangepast."
            redirect_to action: "index"
        else
            flash[:notice] = "Oh nee! Uw klanteninfo kon niet opgeslagen worden."
            render 'edit'
        end
    end
    
    def destroy
        @client.destroy
        redirect_to action: "index"
    end
    
    private
    
    def client_params
        params.require(:client).permit(:client_number, :client_name, :client_contact_person, :client_address, :client_zipcode, :client_residence, :client_gender, :client_phone, :client_email, :client_account_number)
    end
    
    def find_client
       @client = Client.find(params[:id]) 
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end
  
  def dashboard
    @projects = Project.all
  end
end

app/helpers/anualaccounts_helper.rb
module AnualaccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/mileage_helper.rb
module MileageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boekhoudprogramma ZZP'ers</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <body class="nav-md">
  <div class="container body">
  
    <%= render "partials/sidenav" %>
    <%= render "partials/topnav" %>
    
    <%= yield %>
    
    <%= render "partials/footer" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script>
      $(document).ready(function() {
        $('#datatable').DataTable();
      });
    </script>
  </body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Boekhoudprogramma ZZP'ers</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    
    <body style="background:#F7F7F7;">
    
    <div class="container body">
    
      <%= yield %>
    
    </body>
</html>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Boekhoudprogramma - ZZP boekhoudprogramma door <a href="http://www.koendersadvies.nl/">KoendersAdvies</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welkom,</span>
          <h2><%= current_user.user_name %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section"><br>
          <h3>Algemeen</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Algemeen <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li>
                  <%= link_to edit_company_path(current_user.company) do %>
                    Mijn gegevens
                  <% end %>
                </li>
                <li>
                  <%= link_to clients_path do %>
                    Klanten
                  <% end %>
                </li>
                <li>
                  <%= link_to pages_dashboard_path do %>
                    Dashboard
                  <% end %>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-pencil-square-o"></i> Project-registratie <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li>
                  <%= link_to projects_path do %>
                    Projecten
                  <% end %>
                </li>
                <li>
                  <%= link_to timesheets_path do %>
                    Urenregistratie
                  <% end %>
                </li>
                <li><a>Urenoverzicht</a>
                </li>
                <li>
                  <%= link_to mileages_path do %>
                    Kilometerregistratie
                  <% end %>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-credit-card"></i> Transacties <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li>
                  <%= link_to invoices_path do %>
                    Factureren
                  <% end %>
                </li>
                <li><a>Inkomsten</a>
                </li>
                <li>
                <%= link_to spendings_path do %>
                  Uitgaven
                <% end %>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-files-o"></i> Rapportages <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a>BTW aangifte</a>
                </li>
                <li>
                  <%= link_to annualaccounts_path do %>
                    Jaarrekening
                  <% end %>
                </li>
                <li><a>Bankafschriften</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag "img.jpg" %><%= current_user.user_name %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;">  Profile</a>
            </li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">Help</a>
            </li>
            <li>
              <%= link_to destroy_user_session_path, :method => "delete", data: {confirm: "Weet je zeker dat je uit wilt loggen?"} do %>
                <i class="fa fa-sign-out pull-right"></i> Log Out
              <% end %>
            </li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>

      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>')
        <% end %>
    </script>
<% end %>