config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  get 'pages/home'
  get 'pages/dashboard'
  get 'plainpage/index'

  resources :companies
  resources :clients
  resources :projects
  resources :timesheets
  resources :invoices
  resources :spendings
  resources :annualaccounts
  resources :mileages

  get 'companies/edit'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :company
    belongs_to :client
    
    validates :project_name, presence: true
    validates :project_client, presence: true
    validates :project_budget, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_project, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index
        @projects = Project.all
    end
    
    def new
        @project = Project.new
    end
    
    def create
        @project = Project.new client_params
        
        if @project.save
            flash[:notice] = "Het project is opgeslagen!"
            redirect_to action: "index"
        else
            render 'new'
            flash[:notice] = "Oh nee! Het project is niet opgeslagen."
        end
    end
    
    def edit
    end
    
    def update
        if @project.update client_params
            flash[:notice] = "Uw projectinfo is succesvol aangepast."
            redirect_to action: "index"
        else
            flash[:notice] = "Oh nee! Uw projectinfo kon niet opgeslagen worden."
            render 'edit'
        end
    end
    
    def destroy
        @project.destroy
        redirect_to action: "index"
    end
    
    private
    
    def client_params
        params.require(:project).permit(:project_name, :project_client, :project_budget, :project_hour_rate, :project_billable, :project_non_billable, :project_residual)
    end
    
    def find_project
       @project = Project.find(params[:id]) 
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal form-label-left'} do |f| %>
    <% if @project.errors.any? %>
        <h2><%= pluralize(@project.errors.count, "error")%> zorgde ervoor dat de klant niet opgeslagen kon worden.</h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    
    <div class="form-group">
        <%= f.label :project_name, 'Project', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :project_name, class: 'form-control col-md-7 col-xs-12' %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :project_client, 'Klant', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.collection_select(:project_client, Client.all, :client_name, :client_name, include_blank: true, class: 'form-control') %><br>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :project_budget, 'Budget', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :project_budget, class: 'form-control col-md-7 col-xs-12' %><br>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :project_hour_rate, 'Uurtarief', class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.number_field :project_hour_rate, class: 'form-control col-md-7 col-xs-12', :step => '0.01' %><br>
        </div>
    </div>
    
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <%= link_to 'Annuleren', projects_path, :class => 'btn btn-primary' %>
        <%= f.submit 'Opslaan', :class => 'btn btn-success' %>
    </div>
    
<% end %>

app/views/projects/edit.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Edit project</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Wijzig <%= @project.project_name %></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
              <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/projects/index.html.erb
<!-- page content -->
<div class="right_col" role="main" style="height:100vh">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Projecten</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Mijn Projecten</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                    <th class="column-title">Project</th>
                    <th class="column-title">Klant</th>
                    <th class="column-title">Budget</th>
                    <th class="column-title">Uurtarief</th>
                    <th class="column-title">Billable</th>
                    <th class="column-title">Non Billable</th>
                    <th class="column-title">Nog over</th>
                    <th class="column-title"></th>
                </tr>
              </thead>
            <% @projects.each do |project| %>
              <tbody>
                  <tr>
                    <%-# Project -%>
                    <td><%= project.project_name %></td>
                    
                    <%-# Klant -%>
                    <td><%= project.project_client %></td>
                    
                    <%-# Budget -%>
                    <td><%= project.project_budget %> uren</td>
                    
                    <%-# Uurtarief -%>
                    <td>€ <%= project.project_hour_rate %></td>
                    
                    <%-# Billable -%>
                    <td>
                        <% som_hours = 0 %>
                        <% Timesheet.all.each do |timesheet| %>
                            <% if timesheet.timesheet_name == project.project_name && timesheet.timesheet_billable == true %>
                                <% som_hours = som_hours + timesheet.timesheet_hours %>
                            <% end %>
                        <% end %>
                        <% project.project_billable = som_hours %>
                        <%= project.project_billable %> uren
                    </td>
                    
                    <%-# Non Billable -%>
                    <td>
                        <% som_hours = 0 %>
                        <% Timesheet.all.each do |timesheet| %>
                            <% if timesheet.timesheet_name == project.project_name && timesheet.timesheet_billable == false %>
                                <% som_hours = som_hours + timesheet.timesheet_hours %>
                            <% end %>
                        <% end %>
                        <% project.project_non_billable = som_hours %>
                        <%= project.project_non_billable %> uren
                    </td>
                    
                    <%-# Nog over -%>
                    <td>
                        <% project.project_residual = project.project_budget - project.project_billable %>
                        
                        <%= project.project_residual %> uren
                    </td>
                    
                    <%-# Acties -%>
                    <td>
                    <%= link_to edit_project_path(project) do %>
                        <img src="/images/pencil-edit-button.png" alt="Delete" class="edit_icon">
                    <% end %>
                    <%= link_to project_path(project), method: :delete, data: { confirm: "Weet je zeker dat je dit project wilt verwijderen" } do %>
                        <img src="/images/delete.png" alt="Wijzig" class="edit_icon">
                    <% end %>
                    </td>
                  </tr>
              </tbody>
            <% end %>
            </table>
            
            <div class="col-md-6 col-md-offset-5">
                <%= link_to new_project_path do %>
                    <button class="btn btn-primary">Nieuw project</button>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/projects/new.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nieuw project</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Maak een project aan:</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
              <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->