config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  get 'pages/home'
  get 'pages/dashboard'
  get 'plainpage/index'

  resources :companies
  resources :clients
  resources :projects
  resources :timesheets
  resources :invoices
  resources :spendings
  resources :annualaccounts
  resources :mileages

  get 'companies/edit'
  

end

app/models/annualaccount.rb
class Annualaccount < ActiveRecord::Base
    validates :an_date, presence: true
end

app/controllers/annualaccounts_controller.rb
class AnnualaccountsController < ApplicationController
    before_action :find_annualaccount, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @annualaccounts = Annualaccount.all
    end
    
    def new
        @annualaccount = Annualaccount.new
    end
    
    def show
    end
    
    def create
        @annualaccount = Annualaccount.new annualaccount_params
        
        if @annualaccount.save
            flash[:notice] = "De klant is opgeslagen!"
            redirect_to action: "index"
        else
            render 'new'
            flash[:notice] = "Oh nee! De klant is niet opgeslagen."
        end
    end
    
    def edit
    end
    
    def update
        if @annualaccount.update annualaccount_params
            flash[:notice] = "Uw klanteninfo is succesvol aangepast."
            redirect_to action: "index"
        else
            flash[:notice] = "Oh nee! Uw klanteninfo kon niet opgeslagen worden."
            render 'edit'
        end
    end
    
    def destroy
        @annualaccount.destroy
        redirect_to action: "index"
    end
    
    private
    
    def annualaccount_params
        params.require(:annualaccount).permit(:an_date, :an_pr_return, :an_pr_production_cost, :an_pr_gross_margin, :an_pr_TA_expenses, :an_pr_accomodation_expenses, :an_pr_sales_expenses, :an_pr_consumption_expenses, :an_pr_other_expenses, :an_pr_total_other_expenses, :an_pr_net_margin, :an_pr_depreciation, :an_pr_bank_charges, :an_pr_small_business_scheme, :an_pr_loss, :an_pr_withdrawal, :an_pr_deposit, :an_pr_balance_turnover_tax, :an_pr_payed_turnover_tax, :an_pr_deductible_consumption_expenses, :an_ba_debtor, :an_ba_liquid_assets, :an_ba_prepayment, :an_ba_stock, :an_ba_carrying_amount, :an_ba_total_asset, :an_ba_creditors, :an_ba_accrued_receivables, :an_ba_current_receivables, :an_ba_loan, :an_ba_pr_balance, :an_ba_withdrawals_deposits_balance, :an_ba_reserve, :an_ba_total_receivables)
    end
    
    def find_annualaccount
       @annualaccount = Annualaccount.find(params[:id]) 
    end
end

app/views/annualaccounts/_form.html.erb
<%= form_for @annualaccount do |f| %>
    <% if @annualaccount.errors.any? %>
        <h2><%= pluralize(@annualaccount.errors.count, "error")%> zorgde ervoor dat de klant niet opgeslagen kon worden.</h2>
        <ul>
            <% @annualaccount.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    
    <%= f.label :an_date, 'Datum' , class: 'input_label' %>
    <%= f.text_field :an_date, class: 'input_field', id: 'datepicker1', :value => (f.object.an_date.strftime('%Y') if f.object.an_date) %><br>
    
    <%= f.label :an_pr_depreciation, 'Afschrijvingen', class: 'input_label' %>
    <%= f.number_field :an_pr_depreciation, class: 'input_field' %><br>
    
    <%= f.label :an_pr_interest, 'Bankkosten', class: 'input_label' %>
    <%= f.number_field :an_pr_interest, class: 'input_field' %><br>
    
    <div class="center_buttons">
        <%= f.submit 'Opslaan', :class => 'add_button' %>
        <%= link_to 'Annuleren', annualaccounts_path, :class => 'cancel_button' %>
    </div>
    
<% end %>

app/views/annualaccounts/edit.html.erb
<section class="inhoud">
    <div class="navigation2">
        <h1>Wijzig <%= @annualaccount.an_date %></h1>
    </div>

    <%= render 'form' %>
</section>

app/views/annualaccounts/index.html.erb
<!-- page content -->
<div class="right_col" role="main" style="height:100vh">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Jaarrekening</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Mijn jaarrekeningen</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                    <th class="column-title">Datum</th>
                    <th class="column-title">Omzet</th>
                    <th class="column-title"></th>
                </tr>
              </thead>
            <% @annualaccounts.each do |annualaccount| %>
              <tbody>
                  <tr>
                    <td><%= annualaccount.an_date.strftime('%Y') %></td>
                    <td><%= annualaccount.an_pr_return %></td>
                    <td style="width:150px">
                    <%= link_to annualaccount_path(annualaccount) do %>
                        <img src="/images/magnifying-glass.png" alt="Delete" class="edit_icon">
                    <% end %>
                    <%= link_to edit_annualaccount_path(annualaccount) do %>
                        <img src="/images/pencil-edit-button.png" alt="Delete" class="edit_icon">
                    <% end %>
                    <%= link_to annualaccount_path(annualaccount), method: :delete, data: { confirm: "Weet je zeker dat je deze klant wilt verwijderen" } do %>
                        <img src="/images/delete.png" alt="Wijzig" class="edit_icon">
                    <% end %>
                    </td>
                  </tr>
              </tbody>
            <% end %>
            </table>
            <div class="col-md-6 col-md-offset-5">
              <%= link_to new_annualaccount_path do %>
                  <button class="btn btn-primary">Nieuwe W&V rekening</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/annualaccounts/new.html.erb
<section class="inhoud">
    <div class="navigation2">
        <h1>Maak een klant aan:</h1>
    </div>

    <%= render 'form' %>
</section>

app/views/annualaccounts/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Jaarrekening <%= @annualaccount.an_date.year %></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Winst- en verliesrekening</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table class="table2">
                <tbody>
                    <tr>
                        <td>Omzet</td> 
                        <td><%= @annualaccount.an_pr_return %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>    
                    <tr>
                        <td>Productiekosten</td> 
                        <td><%= @annualaccount.an_pr_production_cost %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td class="extra">Brutomarge</td>
                        <td class="extra"><%= @annualaccount.an_pr_gross_margin %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Reis- en verblijfkosten</td> 
                        <td><%= @annualaccount.an_pr_TA_expenses %></td>
                    </tr>
                    <tr>
                        <td>Huisvestingkosten</td> 
                        <td><%= @annualaccount.an_pr_accomodation_expenses %></td>
                    </tr>
                    <tr>
                        <td>Kantoorkostenv</td> 
                        <td><%= @annualaccount.an_pr_sales_expenses %></td>
                    </tr>
                    <tr>
                        <td>Verkoopkosten</td> 
                        <td><%= @annualaccount.an_pr_consumption_expenses %></td> 
                    </tr>
                    <tr>
                        <td>Consumptiekosten</td> 
                        <td><%= @annualaccount.an_pr_other_expenses %></td>
                    </tr>
                    <tr>
                        <td>Andere kosten</td> 
                        <td><%= @annualaccount.an_pr_total_other_expenses %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Totaal overige kosten</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td class="extra">Nettomarge</td> 
                        <td class="extra"><%= @annualaccount.an_pr_net_margin %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Afschrijvingen</td> 
                        <td><%= @annualaccount.an_pr_depreciation %></td>
                    </tr>
                    <tr>
                        <td>Bankkosten (rente negatief vermelden)</td> 
                        <td><%= @annualaccount.an_pr_bank_charges %></td>
                    </tr>
                    <tr>
                        <td>Kleine Ondernemersregeling</td> 
                        <td><%= @annualaccount.an_pr_small_business_scheme %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td class="extra">Verlies afgelopen jaar</td> 
                        <td class="extra"><%= @annualaccount.an_pr_loss %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Privé-onttrekking</td> 
                        <td><%= @annualaccount.an_pr_withdrawal %></td>
                    </tr>
                    <tr>
                        <td>Privé-stortingen</td> 
                        <td><%= @annualaccount.an_pr_deposit %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Salderen omzetbelasting</td> 
                        <td><%= @annualaccount.an_pr_balance_turnover_tax %></td>
                    </tr>
                    <tr>
                        <td>Betaalde omzetbelasting</td> 
                        <td><%= @annualaccount.an_pr_payed_turnover_tax %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Niet aftrekbare consumptiekosten</td> 
                        <td><%= @annualaccount.an_pr_deductible_consumption_expenses %></td>
                    </tr>
                <tbody>
            </table>
          </div>
        </div>
      </div>
    
    <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Balans</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table class="table2">
                <tbody>
                    <tr>
                        <td class="extra"><h4>Activa</h4></td>
                        <td class="extra"><h4><%= @annualaccount.an_date.year %></h4></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Vlottende activa</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Debiteuren</td> 
                        <td><%= @annualaccount.an_ba_debtor %></td>
                    </tr>
                    <tr>
                        <td>Liquide middelen</td> 
                        <td><%= @annualaccount.an_ba_liquid_assets %></td>
                    </tr>
                     <tr>
                        <td>Overlopende active (o.a. omzetbelasting)</td> 
                        <td><%= @annualaccount.an_ba_prepayment %></td>
                    </tr>
                     <tr>
                        <td>Voorraad</td> 
                        <td><%= @annualaccount.an_pr_production_cost %></td> 
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Vaste activa</td>
                        <td></td>
                    </tr>
                     <tr>
                        <td>Boekwaarde</td> 
                        <td><%=@annualaccount.an_ba_carrying_amount %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                     <tr>
                        <td>Totaal Activa</td> 
                        <td><%= @annualaccount.an_ba_total_asset %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td class="extra"><h4>Passiva</h4></td>
                        <td class="extra"><h4><%= @annualaccount.an_date.year %></h4></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Kortlopende schulden</td>
                        <td></td>
                    </tr>
                     <tr>
                        <td>Crediteuren</td> 
                        <td><%= @annualaccount.an_ba_creditors %></td>
                    </tr>
                     <tr>
                        <td>Overlopende passiva (o.a. omzetbelasting)</td> 
                        <td><%= @annualaccount.an_ba_accrued_receivables %></td>
                    </tr>
                     <tr>
                        <td>Kortlopende schulden</td> 
                        <td><%= @annualaccount.an_ba_current_receivables %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Langlopende schulden</td>
                        <td></td>
                    </tr>
                     <tr>
                        <td>Lening</td> 
                        <td><%= @annualaccount.an_ba_loan %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Eigen vermogen</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Saldo winst- en verliesrekening !!!!</td> 
                        <td><%= @annualaccount.an_ba_withdrawals_deposits_balance %></td>
                    </tr>
                    <tr>
                        <td>Saldo priveonttrekkingen - stortingen</td> 
                        <td><%= @annualaccount.an_ba_withdrawals_deposits_balance %></td>
                    </tr>
                    <tr>
                        <td>Reserve</td>
                        <td><%= @annualaccount.an_ba_reserve %></td>
                    </tr>
                    <tr>
                        <td></td> 
                        <td></td>
                    </tr>
                    <tr>
                        <td>Totaal Passiva</td></td> 
                        <td><%= @annualaccount.an_ba_total_receivables %></td>
                    </tr>
                </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>
<!-- /page content -->